// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMGhK6yCX9OwO__mCfiB2239gqN2G8Chw',
    appId: '1:644513616256:web:aa1c5b8bfffae7aaf17165',
    messagingSenderId: '644513616256',
    projectId: 'fir-tp6-783f5',
    authDomain: 'fir-tp6-783f5.firebaseapp.com',
    storageBucket: 'fir-tp6-783f5.firebasestorage.app',
    measurementId: 'G-55NMQYBP01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0brZddVwvScoXBdz3HXpmNAioBN5XxLk',
    appId: '1:644513616256:android:74c9aeeec705b68af17165',
    messagingSenderId: '644513616256',
    projectId: 'fir-tp6-783f5',
    storageBucket: 'fir-tp6-783f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANU5gMCaDx4nPK-hIypOhZhh0kcezgzrI',
    appId: '1:644513616256:ios:98aba576cbfd746bf17165',
    messagingSenderId: '644513616256',
    projectId: 'fir-tp6-783f5',
    storageBucket: 'fir-tp6-783f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANU5gMCaDx4nPK-hIypOhZhh0kcezgzrI',
    appId: '1:644513616256:ios:98aba576cbfd746bf17165',
    messagingSenderId: '644513616256',
    projectId: 'fir-tp6-783f5',
    storageBucket: 'fir-tp6-783f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMGhK6yCX9OwO__mCfiB2239gqN2G8Chw',
    appId: '1:644513616256:web:5de10c7fe48c9e5af17165',
    messagingSenderId: '644513616256',
    projectId: 'fir-tp6-783f5',
    authDomain: 'fir-tp6-783f5.firebaseapp.com',
    storageBucket: 'fir-tp6-783f5.firebasestorage.app',
    measurementId: 'G-QRQ1Y4DJLZ',
  );
}
